version: '3.8'

services:
  app:
    build: .
    container_name: elixir-app
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/elixir_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elixir_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge